### ISSUE TITLE
extended_editable_text版本问题

### ISSUE THREAD

**Issue by shareCourage** [hrxiang/flutter_openim_widget#2]
大佬！你们用的flutter、dart版本多少啊？
我用最新的2.10.1(flutter)、2.16.1(dart)怎么都编译不出来。
报错信息：
`
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:1179:9: Error: Type 'TextEditingActionTarget' not found.
        TextEditingActionTarget,
        ^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:1174:7: Error: The type 'TextEditingActionTarget' can't be mixed in.
class ExtendedEditableTextState extends State<ExtendedEditableText>
      ^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2598:11: Error: Superclass has no method named 'copySelection'.
    super.copySelection(cause);
          ^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2628:11: Error: Superclass has no method named 'cutSelection'.
    super.cutSelection(cause);
          ^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2638:11: Error: Superclass has no method named 'pasteText'.
    super.pasteText(cause);
          ^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2648:11: Error: Superclass has no method named 'selectAll'.
    super.selectAll(cause);
          ^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2693:11: Error: Superclass has no method named 'setSelection'.
    super.setSelection(nextSelection, cause);` 

我分析是extended_editable_text版本低了，但是你们的flutter_openim_widget又依赖9.0.3版本。

**Comment by hrxiang** [comment]
> 大佬！你们用的flutter、dart版本多少啊？ 我用最新的2.10.1(flutter)、2.16.1(dart)怎么都编译不出来。 报错信息： ` ../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:1179:9: Error: Type 'TextEditingActionTarget' not found. TextEditingActionTarget, ^^^^^^^^^^^^^^^^^^^^^^^ ../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:1174:7: Error: The type 'TextEditingActionTarget' can't be mixed in. class ExtendedEditableTextState extends State<ExtendedEditableText> ^ ../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2598:11: Error: Superclass has no method named 'copySelection'. super.copySelection(cause); ^^^^^^^^^^^^^ ../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2628:11: Error: Superclass has no method named 'cutSelection'. super.cutSelection(cause); ^^^^^^^^^^^^ ../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2638:11: Error: Superclass has no method named 'pasteText'. super.pasteText(cause); ^^^^^^^^^ ../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2648:11: Error: Superclass has no method named 'selectAll'. super.selectAll(cause); ^^^^^^^^^ ../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-9.0.3/lib/src/extended_editable_text.dart:2693:11: Error: Superclass has no method named 'setSelection'. super.setSelection(nextSelection, cause);`
> 
> 我分析是extended_editable_text版本低了，但是你们的flutter_openim_widget又依赖9.0.3版本。

flutter pub upgrade

**Comment by shareCourage** [comment]
没用的，你的[flutter_openim_widget] 0.0.5 依赖9.0.3版本
