### ISSUE TITLE
ChatInputBoxView样式定制

### ISSUE THREAD

**Issue by CowSmiles** [hrxiang/flutter_openim_widget#3]
ChatInputBoxView Widget能否提供样式定制的接口，比较背景颜色一类的，麻烦了，多谢。

**Comment by hrxiang** [comment]
空了就加，还有哪些需要，可以一起提了。

**Comment by CowSmiles** [comment]
多谢多谢，暂时还没遇到，遇到了再麻烦您。

**Comment by zhuzhu322** [comment]
请问可以下载到完整的项目文件吗？

**Comment by hrxiang** [comment]
> 请问可以下载到完整的项目文件吗？

完整的？是指demo吗，demo官网的github仓库有

**Comment by simplast** [comment]
能支持自定义的消息类型吗，比如添加一个发红包
