### ISSUE TITLE
iOS模拟器编译不通过，报Undefined symbol错误

### ISSUE THREAD

**Issue by zhuzhu322** [hrxiang/flutter_openim_widget#4]
Error (Xcode): Undefined symbol: _Open_im_sdkGetSelfUserInfo
Error (Xcode): Undefined symbol: _Open_im_sdkGetUsersInfo
Error (Xcode): Undefined symbol: _Open_im_sdkSetUserListener
Error (Xcode): Undefined symbol: _Open_im_sdkSignalingReject
Error (Xcode): Undefined symbol: _Open_im_sdkSignalingAccept
Error (Xcode): Undefined symbol: _Open_im_sdkClearGroupHistoryMessage
Error (Xcode): Undefined symbol: _Open_im_sdkClearC2CHistoryMessage
........

iOS模拟器编译不通过，报Undefined symbol错误，请问如何处理？
![截屏2022-04-25 16 09 20](https://user-images.githubusercontent.com/24912919/165047296-ba312413-f1a1-427b-9186-908e620f37d8.png)

**Comment by hrxiang** [comment]
今天 发布sdk后，不在区分模拟器跟真机，直接可以使用
