### ISSUE TITLE
安卓打包出现问题

### ISSUE THREAD

**Issue by mimiaopp** [hrxiang/flutter_openim_widget#6]
flutter库版本
![image](https://user-images.githubusercontent.com/37366343/174485871-5fc301b4-f9cf-4381-bba9-4676a8483c4c.png)
sdk版本
![Uploading image.png…]()
报错信息
![image](https://user-images.githubusercontent.com/37366343/174485863-176cd217-84f6-46e6-b2c4-e231a647d31b.png)

**Comment by hrxiang** [comment]
更新代码
