### ISSUE TITLE
安卓打包出现问题

### ISSUE THREAD

**Issue by mimiaopp** [hrxiang/flutter_openim_widget#7]
flutter库版本
![image](https://user-images.githubusercontent.com/37366343/174485871-5fc301b4-f9cf-4381-bba9-4676a8483c4c.png)
sdk版本
![image](https://user-images.githubusercontent.com/37366343/174485897-a00c5e6e-a9a7-4edd-af51-43b98708c238.png)
报错信息
![image](https://user-images.githubusercontent.com/37366343/174485863-176cd217-84f6-46e6-b2c4-e231a647d31b.png)

**Comment by mimiaopp** [comment]
flutter doctor
![image](https://user-images.githubusercontent.com/37366343/174485973-02296972-9088-4b0b-8c62-245bc4deae31.png)
请问这个是什么情况

**Comment by hrxiang** [comment]
使用最新代码或sdk

**Comment by mimiaopp** [comment]
使用了2.0.9还是不行

**Comment by mimiaopp** [comment]
sdk 2.0.4是被删掉了吗
